### ISSUE TITLE
Segfault when switching from ffa -> edit after game launch

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#1024]
- Version and build: master
- Observation: Occasionally when starting up the game and running `/ffa <map>` from the titlescreen, the game will crash with signal 11 when running `/edit <map>` shortly afterwards

- How to reproduce:
It's hard to reproduce when it happens normally, as for several minutes into ffa mode. But noticed if you place this command into autoexec.cfg, so that it's run immediately, the game crashes everytime;

`ffa octavus; edit octavus`

I believe this is related to the problem in question; There's a backtrace of that here; 

```
Thread 1 "redeclipse_linu" received signal SIGINT, Interrupt.
0x00007ffff3ae0095 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
(gdb) bt full
#0  0x00007ffff3ae0095 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#1  0x00007ffff3c50333 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#2  0x00007ffff3c50c76 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#3  0x00007ffff3c50ef7 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#4  0x00007ffff3ae0933 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#5  0x00007ffff3ad61a6 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#6  0x00007ffff38e72c8 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#7  0x00007ffff38ec794 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#8  0x00007ffff38ed000 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#9  0x00007ffff4286840 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#10 0x00007ffff428ec36 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#11 0x00007ffff429ce33 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#12 0x00007ffff425c733 in ?? () from /usr/lib64/libnvidia-glcore.so.440.64
No symbol table info available.
#13 0x0000000000665c1c in linkglslprogram (s=..., msg=true) at engine/shader.cpp:370
        attribs = 0
        success = 0
#14 0x0000000000667655 in Shader::compile (this=0x2807b618) at engine/shader.cpp:716
No locals.
#15 0x000000000066810c in newshader (type=0, name=0x2bee586c "waterminimap", 
    vs=0x2bee5880 "\n    attribute vec4 vvertex;\n    uniform mat4 camprojmatrix;\n    \n        uniform vec2 lineardepthscale;\n        uniform vec3 gdepthpackparams;\n        varying float lineardepth;\n    \n    void main(vo"..., 
    ps=0x2bee59d8 "\n    uniform vec3 watercolor;\n    \n        fragdata(0) vec4 gcolor;\n        fragdata(1) vec4 gnormal;\n        \n", ' ' <repeats 12 times>, "fragdata(2) vec4 gdepth;\n", ' ' <repeats 12 times>, "fragdata(3) vec4 gglow;\n        \n       "..., 
    variant=0x0, row=0) at engine/shader.cpp:819
        exists = 0x2807b618
        rname = 0x28140a90 "waterminimap"
        s = @0x2807b618: {static lastshader = 0x0, name = 0x28140a90 "waterminimap", 
          vsstr = 0x2ddd8410 "\n    attribute vec4 vvertex;\n    uniform mat4 camprojmatrix;\n    \n        uniform vec2 lineardepthscale;\n        uniform vec3 gdepthpackparams;\n        varying float lineardepth;\n    \n    void main(vo"..., 
          psstr = 0x2dd4cf40 "\n    uniform vec3 watercolor;\n    \n        fragdata(0) vec4 gcolor;\n        fragdata(1) vec4 gnormal;\n        \n", ' ' <repeats 12 times>, "fragdata(2) vec4 gdepth;\n", ' ' <repeats 12 times>, "fragdata(3) vec4 gglow;\n        \n       "..., defer = 0x0, type = 0, program = 667, vsobj = 665, psobj = 666, defaultparams = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}, globalparams = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}, localparams = {static MINSIZE = 8, buf = 0x0, alen = 0, 
            ulen = 0}, localparamremap = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}, variantshader = 0x0, variants = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}, variantrows = 0x0, standard = true, forced = false, used = false, reusevs = 0x0, 
          reuseps = 0x0, uniformlocs = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}, attriblocs = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}, fragdatalocs = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}, owner = 0x0}
#16 0x00000000006695a1 in shader (type=0x7fffffff8050, name=0x2bee586c "waterminimap", 
    vs=0x2bee5880 "\n    attribute vec4 vvertex;\n    uniform mat4 camprojmatrix;\n    \n        uniform vec2 lineardepthscale;\n        uniform vec3 gdepthpackparams;\n        varying float lineardepth;\n    \n    void main(vo"..., 
    ps=0x2bee59d8 "\n    uniform vec3 watercolor;\n    \n        fragdata(0) vec4 gcolor;\n        fragdata(1) vec4 gnormal;\n        \n", ' ' <repeats 12 times>, "fragdata(2) vec4 gdepth;\n", ' ' <repeats 12 times>, "fragdata(3) vec4 gglow;\n        \n       "...)
    at engine/shader.cpp:1081
        vsbuf = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}
        psbuf = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}
        vsbak = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}
        psbak = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}
        s = 0x7fffffff85f0
#17 0x00000000004dc82c in runcode (code=0x2bee5cec, result=...) at engine/command.cpp:2974
        id = 0xc124e8
        offset = 0
--Type <RET> for more, q to quit, c to continue without paging--c
        op = 426521
        numargs = 4
        args = {{<identval> = {{i = 0, f = 0, s = 0x7fff00000000 <error: Cannot access memory at address 0x7fff00000000>, code = 0x7fff00000000, id = 0x7fff00000000, cstr = 0x7fff00000000 <error: Cannot access memory at address 0x7fff00000000>}}, type = 1}, {<identval> = {{i = 737040492, f = 1.69354591e-12, s = 0x2bee586c "waterminimap", code = 0x2bee586c, id = 0x2bee586c, cstr = 0x2bee586c "waterminimap"}}, type = 6}, {<identval> = {{i = 737040512, f = 1.69354808e-12, s = 0x2bee5880 "\n    attribute vec4 vvertex;\n    uniform mat4 camprojmatrix;\n    \n        uniform vec2 lineardepthscale;\n        uniform vec3 gdepthpackparams;\n        varying float lineardepth;\n    \n    void main(vo"..., code = 0x2bee5880, id = 0x2bee5880, cstr = 0x2bee5880 "\n    attribute vec4 vvertex;\n    uniform mat4 camprojmatrix;\n    \n        uniform vec2 lineardepthscale;\n        uniform vec3 gdepthpackparams;\n        varying float lineardepth;\n    \n    void main(vo"...}}, type = 6}, {<identval> = {{i = 737040856, f = 1.69358538e-12, s = 0x2bee59d8 "\n    uniform vec3 watercolor;\n    \n        fragdata(0) vec4 gcolor;\n        fragdata(1) vec4 gnormal;\n        \n", ' ' <repeats 12 times>, "fragdata(2) vec4 gdepth;\n", ' ' <repeats 12 times>, "fragdata(3) vec4 gglow;\n        \n       "..., code = 0x2bee59d8, id = 0x2bee59d8, cstr = 0x2bee59d8 "\n    uniform vec3 watercolor;\n    \n        fragdata(0) vec4 gcolor;\n        fragdata(1) vec4 gnormal;\n        \n", ' ' <repeats 12 times>, "fragdata(2) vec4 gdepth;\n", ' ' <repeats 12 times>, "fragdata(3) vec4 gglow;\n        \n       "...}}, type = 6}, {<identval> = {{i = 9649519, f = 1.35218562e-38, s = 0x933d6f "%s.mpz", code = 0x933d6f, id = 0x933d6f, cstr = 0x933d6f "%s.mpz"}}, type = -144040992}, {<identval> = {{i = -32368, f = -nan(0x7f8190), s = 0x7fffffff8190 "", code = 0x7fffffff8190, id = 0x7fffffff8190, cstr = 0x7fffffff8190 ""}}, type = -144041088}, {<identval> = {{i = 1296, f = 1.81608281e-42, s = 0x510 <error: Cannot access memory at address 0x510>, code = 0x510, id = 0x510, cstr = 0x510 <error: Cannot access memory at address 0x510>}}, type = -144041088}, {<identval> = {{i = 1312, f = 1.83850359e-42, s = 0x520 <error: Cannot access memory at address 0x520>, code = 0x520, id = 0x520, cstr = 0x520 <error: Cannot access memory at address 0x520>}}, type = 82}, {<identval> = {{i = 110, f = 1.54142831e-43, s = 0x6e <error: Cannot access memory at address 0x6e>, code = 0x6e, id = 0x6e, cstr = 0x6e <error: Cannot access memory at address 0x6e>}}, type = -145400461}, {<identval> = {{i = 737040464, f = 1.69354288e-12, s = 0x2bee5850 "", code = 0x2bee5850, id = 0x2bee5850, cstr = 0x2bee5850 ""}}, type = -144040992}, {<identval> = {{i = 7, f = 9.80908925e-45, s = 0x7 <error: Cannot access memory at address 0x7>, code = 0x7, id = 0x7, cstr = 0x7 <error: Cannot access memory at address 0x7>}}, type = 12087472}, {<identval> = {{i = 1296, f = 1.81608281e-42, s = 0x510 <error: Cannot access memory at address 0x510>, code = 0x510, id = 0x510, cstr = 0x510 <error: Cannot access memory at address 0x510>}}, type = 68}, {<identval> = {{i = 12087952, f = 1.69388286e-38, s = 0xb87290 "", code = 0xb87290, id = 0xb87290, cstr = 0xb87290 ""}}, type = 1344}, {<identval> = {{i = 20, f = 2.80259693e-44, s = 0x14 <error: Cannot access memory at address 0x14>, code = 0x14, id = 0x14, cstr = 0x14 <error: Cannot access memory at address 0x14>}}, type = 82}, {<identval> = {{i = 2, f = 2.80259693e-45, s = 0x2 <error: Cannot access memory at address 0x2>, code = 0x2, id = 0x2, cstr = 0x2 <error: Cannot access memory at address 0x2>}}, type = 0}, {<identval> = {{i = 0, f = 0, s = 0x0, code = 0x0, id = 0x0, cstr = 0x0}}, type = 124}, {<identval> = {{i = 110, f = 1.54142831e-43, s = 0x5d0000006e <error: Cannot access memory at address 0x5d0000006e>, code = 0x5d0000006e, id = 0x5d0000006e, cstr = 0x5d0000006e <error: Cannot access memory at address 0x5d0000006e>}}, type = 14449}, {<identval> = {{i = -32336, f = -nan(0x7f81b0), s = 0x7fffffff81b0 "`\340\377\377\377\177", code = 0x7fffffff81b0, id = 0x7fffffff81b0, cstr = 0x7fffffff81b0 "`\340\377\377\377\177"}}, type = 80}, {<identval> = {{i = 1296, f = 1.81608281e-42, s = 0x510 <error: Cannot access memory at address 0x510>, code = 0x510, id = 0x510, cstr = 0x510 <error: Cannot access memory at address 0x510>}}, type = -144041088}, {<identval> = {{i = -8096, f = -nan(0x7fe060), s = 0x7fffffffe060 "\001", code = 0x7fffffffe060, id = 0x7fffffffe060, cstr = 0x7fffffffe060 "\001"}}, type = 0}, {<identval> = {{i = 0, f = 0, s = 0x0, code = 0x0, id = 0x0, cstr = 0x0}}, type = 673285705}, {<identval> = {{i = -32288, f = -nan(0x7f81e0), s = 0x7fffffff81e0 "\020\202\377\377\377\177", code = 0x7fffffff81e0, id = 0x7fffffff81e0, cstr = 0x7fffffff81e0 "\020\202\377\377\377\177"}}, type = 133689944}, {<identval> = {{i = -8096, f = -nan(0x7fe060), s = 0x7fffffffe060 "\001", code = 0x7fffffffe060, id = 0x7fffffffe060, cstr = 0x7fffffffe060 "\001"}}, type = 0}, {<identval> = {{i = 0, f = 0, s = 0x0, code = 0x0, id = 0x0, cstr = 0x0}}, type = 4297717}, {<identval> = {{i = 1986622064, f = 1.18371703e+33, s = 0x656e6f6e76697270 <error: Cannot access memory at address 0x656e6f6e76697270>, code = 0x656e6f6e76697270, id = 0x656e6f6e76697270, cstr = 0x656e6f6e76697270 <error: Cannot access memory at address 0x656e6f6e76697270>}}, type = 751650352}, {<identval> = {{i = -32240, f = -nan(0x7f8210), s = 0x7fffffff8210 "@\202\377\377\377\177", code = 0x7fffffff8210, id = 0x7fffffff8210, cstr = 0x7fffffff8210 "@\202\377\377\377\177"}}, type = 5202016}, {<identval> = {{i = 10855840, f = 1.52122719e-38, s = 0x12200a5a5a0 <error: Cannot access memory at address 0x12200a5a5a0>, code = 0x12200a5a5a0, id = 0x12200a5a5a0, cstr = 0x12200a5a5a0 <error: Cannot access memory at address 0x12200a5a5a0>}}, type = -31232}, {<identval> = {{i = 737040856, f = 1.69358538e-12, s = 0x2bee59d8 "\n    uniform vec3 watercolor;\n    \n        fragdata(0) vec4 gcolor;\n        fragdata(1) vec4 gnormal;\n        \n", ' ' <repeats 12 times>, "fragdata(2) vec4 gdepth;\n", ' ' <repeats 12 times>, "fragdata(3) vec4 gglow;\n        \n       "..., code = 0x2bee59d8, id = 0x2bee59d8, cstr = 0x2bee59d8 "\n    uniform vec3 watercolor;\n    \n        fragdata(0) vec4 gcolor;\n        fragdata(1) vec4 gnormal;\n        \n", ' ' <repeats 12 times>, "fragdata(2) vec4 gdepth;\n", ' ' <repeats 12 times>, "fragdata(3) vec4 gglow;\n        \n       "...}}, type = -32128}, {<identval> = {{i = -32192, f = -nan(0x7f8240), s = 0x7fffffff8240 "\300\202\377\377\377\177", code = 0x7fffffff8240, id = 0x7fffffff8240, cstr = 0x7fffffff8240 "\300\202\377\377\377\177"}}, type = 5197694}, {<identval> = {{i = -32192, f = -nan(0x7f8240), s = 0x7fffffff8240 "\300\202\377\377\377\177", code = 0x7fffffff8240, id = 0x7fffffff8240, cstr = 0x7fffffff8240 "\300\202\377\377\377\177"}}, type = 5197454}, {<identval> = {{i = -31232, f = -nan(0x7f8600), s = 0x5dffff8600 <error: Cannot access memory at address 0x5dffff8600>, code = 0x5dffff8600, id = 0x5dffff8600, cstr = 0x5dffff8600 <error: Cannot access memory at address 0x5dffff8600>}}, type = -31232}, {<identval> = {{i = -32064, f = -nan(0x7f82c0), s = 0x7fffffff82c0 "\200\203\377\377\377\177", code = 0x7fffffff82c0, id = 0x7fffffff82c0, cstr = 0x7fffffff82c0 "\200\203\377\377\377\177"}}, type = 5059610}}
        prevret = 0xa88ad0 <noret>
#18 0x00000000004e3a5e in execute (p=0x28218230 "\n        shader 0 waterminimap [\n    attribute vec4 vvertex;\n    uniform mat4 camprojmatrix;\n    \n        uniform vec2 lineardepthscale;\n        uniform vec3 gdepthpackparams;\n        varying float li"...) at engine/command.cpp:3292
        code = {static MINSIZE = 8, buf = 0x2bee5860, alen = 324, ulen = 292}
        result = {<identval> = {{i = 0, f = 0, s = 0x0, code = 0x0, id = 0x0, cstr = 0x0}}, type = 0}
        i = 0
#19 0x00000000004e3af7 in execute (p=0x28218230 "\n        shader 0 waterminimap [\n    attribute vec4 vvertex;\n    uniform mat4 camprojmatrix;\n    \n        uniform vec2 lineardepthscale;\n        uniform vec3 gdepthpackparams;\n        varying float li"..., nonworld=true) at engine/command.cpp:3303
        oldflags = 16
        result = 11958896
#20 0x000000000066904e in Shader::force (this=0x2807b618) at engine/shader.cpp:1033
        cmd = 0x28218230 "\n        shader 0 waterminimap [\n    attribute vec4 vvertex;\n    uniform mat4 camprojmatrix;\n    \n        uniform vec2 lineardepthscale;\n        uniform vec3 gdepthpackparams;\n        varying float li"...
        wasstandard = false
        wasforcing = true
#21 0x0000000000669203 in useshaderbyname (name=0x932e55 "waterminimap") at engine/shader.cpp:1058
        s = 0x2807b618
#22 0x00000000006cc21d in preloadwatershaders (force=false) at engine/water.cpp:433
        needwater = true
#23 0x00000000006c8ab7 in var_causticmillis (id=0xc27e90) at engine/water.cpp:27
No locals.
#24 0x00000000004f3be6 in ident::changed (this=0xc27e90) at shared/command.h:190
No locals.
#25 0x00000000004cf7c5 in setvar (name=0x932ed6 "causticmillis", i=75, dofunc=true, def=false, force=false) at engine/command.cpp:729
        id = 0xc27e90
#26 0x00000000006daac8 in clearworldvars (msg=false) at engine/world.cpp:1177
        id = @0xc27e90: {type = 0 '\000', {valtype = 209 '\321', numargs = 209 '\321'}, flags = 48, index = 2096, level = 0, name = 0x932ed6 "causticmillis", {{{{minval = 0, maxval = 1000}, {minvalf = 0, maxvalf = 1.40129846e-42}}, storage = {p = 0xb6b8c4 <causticmillis>, i = 0xb6b8c4 <causticmillis>, f = 0xb6b8c4 <causticmillis>, s = 0xb6b8c4 <causticmillis>}, overrideval = {{i = 12713376, f = 1.78152343e-38, s = 0xc1fda0 "", code = 0xc1fda0, id = 0xc1fda0, cstr = 0xc1fda0 ""}}, def = {{i = 75, f = 1.05097385e-43, s = 0x4b <error: Cannot access memory at address 0x4b>, code = 0x4b, id = 0x4b, cstr = 0x4b <error: Cannot access memory at address 0x4b>}}, bin = {{i = 75, f = 1.05097385e-43, s = 0x4b <error: Cannot access memory at address 0x4b>, code = 0x4b, id = 0x4b, cstr = 0x4b <error: Cannot access memory at address 0x4b>}}}, {code = 0x3e800000000, val = {{i = 11974852, f = 1.67803417e-38, s = 0xb6b8c4 <causticmillis> "K", code = 0xb6b8c4 <causticmillis>, id = 0xb6b8c4 <causticmillis>, cstr = 0xb6b8c4 <causticmillis> "K"}}, stack = 0xc1fda0}, {args = 0x3e800000000 <error: Cannot access memory at address 0x3e800000000>, argmask = 11974852}}, fun = 0x6c8aa1 <var_causticmillis(ident*)>, desc = 0x0, fields = {static MINSIZE = 8, buf = 0x0, alen = 0, ulen = 0}}
        ec = 0xbabb10
        i = 33
#27 0x00000000006e33db in load_world (mname=0xb70100 <client::parsemessages(int, gameent*, databuf<unsigned char>&)::text> "octavus", crc=-1, variant=1) at engine/worldio.cpp:1010
        samegame = true
        lightmaps = 0
        ws = 32767
        ents = @0xa8a860: {static MINSIZE = 8, buf = 0x3038363131370030, alen = 0, ulen = 0}
        importedsunpitch = 0
        fname = "\000\000\000\000\377\177", '\000' <repeats 22 times>, "\001", '\000' <repeats 59 times>, "\002\000\000\000\000\000\000\000\070\372\061(\000\000\000\000\005\000\000\000\377\177\000\000\220\360\377-\000\000\000\000-|\304\363\377\177\000\000\220\211\377\377\377\177\000\000p\276\377-\000\000\000\000\060\235\060\365\377\177\000\000\065\000\000\000\000\000\000\000\bN\n.\000\000\000\000\253|\304\363\377\177\000\000\020\273\377-", '\000' <repeats 12 times>, "\a\000\000\000\000\000\000\000"...
        f = 0x2c2f75a0
        failed = 48
        newhdr = {<binary> = {head = "MAPZ", version = 50, headersize = 44}, worldsize = 32767, numents = 772506512, numpvs = 0, blendmap = 3, numvslots = 48, gamever = -28528, revision = 32767, gameid = "\000\000\000"}
        nummru = 0
        buf = 0xa8a860 <retbuf+512> "0"
        cfgname = "\240E\034(\000\000\000\000\003\000\000\000\000\000\000\000 E\034(\000\000\000\000\003\000\000\000\377\177\000\000@\303\356-\000\000\000\000\003\000\000\000\377\177\000\000`_\310,\000\000\000\000\003\000\000\000\000\000\000\000\320e\016.\000\000\000\000\003\000\000\000\377\177\000\000`\003\343-\000\000\000\000\003\000\000\000\022\000\000\000\320\356\000\b\000\000\000\000\003\000\000\000\377\177\000\000\300\253\367\003\000\000\000\000\003\000\000\000\000\000\000\000P.\003.\000\000\000\000\003\000\000\000\000\000\000\000\320|\254-\000\000\000\000\003\000\000\000\000\000\000\000p\255\377\377\377\177\000\000\000\000\000@\000\000\000\000\200\255\377\377\377\177\000\000\200\255\377\377\377\177\000\000\320\023\340\002\000\000\000\000"...
        filecrc = 1764142989
        importedsuns = -135963470
        importedsunyaw = 0
        importedsuncolor = {{{x = -4.32185727e+33, y = 4.59163468e-41, z = 1.54887649e-38}, {r = -4.32185727e+33, g = 4.59163468e-41, b = 1.54887649e-38}, v = {-4.32185727e+33, 4.59163468e-41, 1.54887649e-38}}}
        tempfile = 0
        loadingstart = 25018
#28 0x000000000070b433 in client::changemapserv (name=0xb70100 <client::parsemessages(int, gameent*, databuf<unsigned char>&)::text> "octavus", gamemode=1, mutators=1, crc=-1, variant=1) at game/client.cpp:1648
No locals.
#29 0x000000000070fdd5 in client::parsemessages (cn=-1, d=0x0, p=...) at game/client.cpp:2562
        mode = 1
        muts = 1
        crc = -1
        variant = 1
        text = "octavus\000\060\061\061\062]\f($privnonetex)\f[7368816]unixfreak\fS forced: \fs\fyEditing\fS on \fs\fooctavus\fS", '\000' <repeats 4911 times>
        type = 30
        prevtype = -1
#30 0x0000000000716ef8 in client::parsepacketclient (chan=1, p=...) at game/client.cpp:3871
No locals.
#31 0x00000000004cc33f in localservertoclient (chan=1, packet=0x2da06fc0) at engine/client.cpp:238
        p = {<databuf<unsigned char>> = {buf = 0x2e0b9720 "\036octavus", len = 13, maxlen = 13, flags = 0 '\000'}, packet = 0x2da06fc0, growth = 0}
#32 0x000000000065c337 in sendpacket (n=0, chan=1, packet=0x2da06fc0, exclude=-1) at engine/server.cpp:482
No locals.
#33 0x000000000065c245 in sendpacket (n=-1, chan=1, packet=0x2da06fc0, exclude=-1) at engine/server.cpp:463
        i = 0
#34 0x000000000065c91a in sendf (cn=-1, chan=1, format=0x9726e1 "") at engine/server.cpp:536
        exclude = -1
        reliable = true
        p = {<databuf<unsigned char>> = {buf = 0x2e0b9720 "\036octavus", len = 13, maxlen = 13, flags = 0 '\000'}, packet = 0x2da06fc0, growth = 5000}
        args = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffffffa398, reg_save_area = 0x7fffffffa2c0}}
#35 0x0000000000851bd5 in server::changemap (name=0x7f7f258 "octavus", mode=1, muts=1) at game/server.cpp:3517
        hastime = false
        reqmap = 0x7f7f258 "octavus"
#36 0x00000000008488ce in server::vote (reqmap=0x7fffffffbfb0 "octavus", reqmode=@0x7fffffffbf2c: 1, reqmuts=@0x7fffffffbf28: 1, sender=0) at game/server.cpp:2838
        ci = 0x7f7e0a0
        israndom = false
        hasvote = false
        hasveto = true
#37 0x0000000000868dd2 in server::parsepacket (sender=0, chan=1, p=...) at game/server.cpp:6930
        s = 0x7fffffffbfb0 "octavus"
        reqmode = 1
        reqmuts = 1
        curtype = 31
        text = "octavus\000avus\000\000\200?8 \021(\000\000\000\000\006\000\000\000\000\000\000\000P]\356-\000\000\000\000\b\000\000\000\001\000\000\000d \021(\000\000\000\000\006\000\000\000\000\000\000\000P]\356-\000\000\000\000\b\000\000\000\000\000\000\000\234 \021(\000\000\000\000\006\000\000\000\000\000\200?\200\307\377\377\377\177\000\000\340\332\321+\000\000\000\000\000\002\000\000\000\000\000\000\001\000\000\000\000\000\000\000\204E\000.\000\000\000\000\300\332\321+\000\000\000\000\220\300\377\377\377\177\000\000\326>j\000\000\000\000\000\240\300\377\377\377\177\000\000~fA\000\000\000\000\000\200\307\377\377\377\177\000\000\220\332\321+\000\000\000\000\220\300\377\377\377\177\000\000"...
        type = 31
        prevtype = 105
        ci = 0x7f7e0a0
        curmsg = 50
#38 0x000000000065d1dd in process (packet=0x3f7abc0, sender=0, chan=1) at engine/server.cpp:627
        p = {<databuf<unsigned char>> = {buf = 0x2e0b8390 "junixfreak", len = 61, maxlen = 65, flags = 0 '\000'}, packet = 0x3f7abc0, growth = 0}
#39 0x000000000065d2ab in localclienttoserver (chan=1, packet=0x3f7abc0) at engine/server.cpp:635
        c = 0x7eca590
#40 0x00000000004cc2ae in sendclientpacket (packet=0x3f7abc0, chan=1) at engine/client.cpp:221
No locals.
#41 0x000000000070e13b in client::sendmessages () at game/client.cpp:2218
        p = {<databuf<unsigned char>> = {buf = 0x2e0b8390 "junixfreak", len = 65, maxlen = 65, flags = 0 '\000'}, packet = 0x3f7abc0, growth = 5000}
#42 0x000000000070e1a3 in client::c2sinfo (force=false) at game/client.cpp:2227
        lastupdate = 25008
#43 0x0000000000769d78 in game::updateworld () at game/game.cpp:3190
No locals.
#44 0x000000000051860e in main (argc=1, argv=0x7fffffffe068) at engine/main.cpp:1132
        elapsed = 10949
        frameloops = 3
        initscript = 0x0
        reprotoprefix = "redeclipse://"
        reprotolen = 13
        reprotoarg = 0x0
        connectstr = 0x0
        connectpassword = 0x0
        connecthost = 0x0
        connectport = 28801
        shouldload = true
(gdb) 

```

As for this line:
`#15 0x000000000066810c in newshader (type=0, name=0x2bee586c "waterminimap", `
I decided to re run the same test, with `/showminimap 0` set, and this does pass the crash (but then introduces mass flickering of lights).

If it's important (as it mentions nvidia libs); my gpu is;
* GTX 1060 3GB
* Driver version, 440.64

**Comment by Jigoku** [comment]
Haven't seen this happen since 440.64, going to assume there was something up with that driver release.
